version: 1
labels:
  - label: "TestLabel"
    title: ".*"
	- label: "NegativeLookahead"
		files:
			-	"^(?!.*test.lock)"
  - label: "TestFileMatch"
    files:
      - "cmd/.*.go"
      - "pkg/.*.go"

