version: 1
labels:
  - label: S
    size-below: 10
    size-above: 1
  - label: M
    size:
      exclude-files: ["test.yaml"]
      above: 9
      below: 100
  - label: L
    size:
      exclude-files: ["test.yaml", "\\/dir\\/test.+.yaml"]
      above: 100
