name: Label PRs with published action as canary

on:
    - pull_request
    - issues

jobs:
  apply_labels:

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
